[Service]
Environment="PATH=/usr/bin:/opt/{{SERVICE_USER}}/bin:/usr/local/bin:/bin:/home/{{SERVICE_USER}}/bin:/home/{{SERVICE_USER}}/.local/bin:/home/{{SERVICE_USER}}/.npm-system-global/bin"
Environment="SHELL=/opt/{{SERVICE_USER}}/libexec/project-shell"
