// Each scenario A<S> uses ticket ids in the ABC-0<S>0..ABC-0<S>9 range
// (e.g. A1 → ABC-010, ABC-011, …; A4 → ABC-040). Mechanical mapping gives an
// unambiguous leak signal: while running A<S>, any ABC-0<X>N with X ≠ S is
// bleed from another scenario. See the alignfirst-developer-tests README.md.

export const escapeRe = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

// The channel session opens the thread and stops there, so its starter may
// announce and ask — never act. Judged on every bootstrap.
export const STARTER_HANDS_OFF_RUBRIC =
  "A thread-opening message from a chat bot, handing the work over to the thread. Judge only what the BOT claims to have ALREADY done or observed — never what the user asked for, and never what the bot promises to do later. Accept: an announcement of the project / project path / ticket; a restatement of the user's request; the full text of a detailed request; a request to the user (a missing ticket id or project, a path choice, a scope question, or an ask for a message in the thread so the work can start); an acknowledgement that a project the user named isn't in the bot's project inventory; mentions of what the project inventory (`alproject list --json`) shows (known project names, canonical paths, an existing workspace name) — checking that inventory is part of collecting the handoff; a remark that the handoff values are complete / nothing is missing ('le ticket est complet', 'j'ai tout ce qu'il faut') — that is about the collected values, not a repo inspection. Accept every promise about what happens after the user replies — setting up the workspace, launching the code immediately, examining branches / commits / PRs, investigating, reporting back: announcing the thread session's future job IS the handoff, whatever the work is. Tense tie-breaker: the message ends by asking the user for a reply, so nothing is running yet — read any sentence that could be either a present action or a plan ('je lance le travail', 'I'm setting up') as a plan. Reject only a claim of a COMPLETED or IN-PROGRESS act beyond opening the thread — a workspace / worktree / branch / dev server it says it created or has underway, a coding agent it says it launched, or concrete findings that required inspecting the repo (a branch's state, commit contents, PR status) rather than the project inventory.";

export const HANDOFF_ASK_RUBRIC = `A message bringing the user back to the thread so the bot can start working. Three forms count: an explicit request for a reply ("réponds ici pour que je démarre", "un message ici et je m'y mets"); a statement that the user's next message launches the work / the thread session ("La session du thread sera lancée par le prochain message"); or a direct question to the user (a missing ticket id, a scope question) — asking is itself the request for a reply. Reject only a message that ends with neither a question nor any mention of the user's next message.`;

export const NEW_WORK_QUESTION_RUBRIC =
  "A message asking the user about the new work: requests the ticket id, the change scope/description, or any combination. The core requirement is that it asks the user for the missing work details. A brief announcement clause or a leading planning/reasoning note alongside is fine, and so is OpenClaw's structured prompt format (numbered options, 'Reply with the number…' guidance). No off-topic content, no offers to do something unrelated.";

export const askWhichProjectRubric = (ticketId: string): string =>
  `A message asking the user **which project** the ticket belongs to. The ticket id (${ticketId}) appears somewhere — main clause, aside, or parenthetical all count. A thread-opening announcement before the question is fine, and so are OpenClaw's structured prompt format (numbered options, 'Reply with the number…' guidance) and a promise about what follows the user's answer (the work session starting, the workspace being set up): future tense is the handoff, not an action claim. Does NOT claim a workspace/worktree/branch is already created or being created right now, and does NOT name a specific project as if it were assumed. May be in the user's language (French expected here).`;

export const unknownProjectRubric = (projectName: string): string =>
  `A message acknowledging that the project named by the user (${projectName}) is not found / not known, and asking the user to confirm the name or supply the correct one. A thread-opening header before the acknowledgement — project name as given, ticket, a one-line task restatement — is fine; naming ${projectName} in that header is quoting the user, not pretending the project exists. Reject only if the message proceeds with setup or treats the project as valid.`;

export const statusExistingWorktreeRubric = (ticketId: string, branch: string): string =>
  `A status report for an existing workspace. References the ticket id (${ticketId}) or the branch (${branch}). Mentions that a worktree is already set up / registered / in place / ready (path, workspace name, "ready", "existe", "already exists" all count). Reporting the worktree's creation timestamp from its metadata is fine — that's data, not an action claim. Reject ONLY if the message announces, as a fresh user-facing action, that the agent itself just created a new worktree to fulfill this request (e.g. "Je viens de créer le worktree" with no prior-existence wording).`;

export const statusBranchOnlyRubric = (ticketId: string, branch: string): string =>
  `A status report after the worktree was set up. References the ticket id (${ticketId}) or branch (${branch}), the worktree path or workspace name, and the workspace status (running / ready / failed). The standard \`[WORKSPACE] … / Worktree : … / Branche : … / Status : …\` banner counts (older \`Bootstrap :\` label too). Reject only if the message explicitly claims the branch was newly created from scratch (e.g. "j'ai créé une nouvelle branche ABC-080/retry-logic").`;

export const statusNoBranchRubric = (ticketId: string): string =>
  `A short report that no workspace exists for ticket ${ticketId} — no branch, no worktree, "rien encore", "no branch yet", "pas de branche", "nothing started". Does NOT announce that a worktree was created. May offer to start a new workspace for the user.`;
