export const PRIMARY_PROJECT_PARENT = "/home/claw/projects";
export const EXTERNAL_PROJECT_PARENT = `${PRIMARY_PROJECT_PARENT}/external-projects`;
export const LIFECYCLE_PROJECT_PARENT = `${PRIMARY_PROJECT_PARENT}/lifecycle-projects`;
export const PROJECT_CONFIG_FILENAME = ".alignfirst.json";

export const NIMBUS_PROJECT_PATH = `${PRIMARY_PROJECT_PARENT}/nimbus`;
export const LUMEN_PROJECT_PATH = `${PRIMARY_PROJECT_PARENT}/lumen`;
export const ORION_PROJECT_PATH = `${EXTERNAL_PROJECT_PARENT}/orion`;
export const NOVA_PROJECT_PATH = `${LIFECYCLE_PROJECT_PARENT}/nova`;

export const FIXTURE_PROJECT_PATHS = [NIMBUS_PROJECT_PATH, LUMEN_PROJECT_PATH, ORION_PROJECT_PATH];
