#!/usr/bin/env node
import { spawn, spawnSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";

const TEMPLATE = "/opt/alignfirst-developer-tests/fixtures/template";
const PRIMARY = "/home/claw/projects";
const EXTERNAL = `${PRIMARY}/external-projects`;
const LIFECYCLE = `${PRIMARY}/lifecycle-projects`;
const PRIMARY_MARKER = {
  description:
    "Managed projects of the AlignFirst Developer test fixture. Adding a project is an operator's decision: ask before creating one.",
  portRange: { first: 6500, last: 7700 },
};
const EXTERNAL_MARKER = {
  description: "Projects hosted for external teams.",
  portRange: { first: 6540, last: 6599 },
};
const LIFECYCLE_MARKER = {
  description:
    "Allowed parent for new lifecycle fixtures. Create Node.js projects with pnpm. Keep bootstrap work and the initial commit on main. Claim a port block with free-ports before writing the project config.",
  portRange: { first: 6600, last: 6699 },
};
// Each fixture gets its own port block so two of them can run a dev server at
// the same time. The template declares `maxWorkspaces: 10` over `perWorkspace: 2`,
// so a fixture spans 20 ports from its base.
const FIXTURES = [
  { name: "nimbus", parent: PRIMARY, basePort: 6500 },
  { name: "lumen", parent: PRIMARY, basePort: 6520 },
  { name: "orion", parent: EXTERNAL, basePort: 6540 },
];
// Each fixture's `origin` is a bare repo alongside its working tree, so
// `git fetch` + `git merge --ff-only origin/main` behave like a real up-to-date
// clone (a remote-less fixture made the playbook's new-work path — fetch +
// fast-forward the base — hard-fail with "origin/main - not something we can
// merge"). Kept out of PROJECTS so it never reads as a project directory.
const ORIGINS = "/home/claw/.fixture-origins";
const BASE_BRANCH = "main";

async function main() {
  // Stop dev-servers from the prior run before wiping. Configured fixtures
  // know their `dev down --all`; for any stray dir we kill anything still
  // listening best-effort.
  for (const { name, parent } of FIXTURES) {
    const dst = `${parent}/${name}`;
    if (existsSync(dst)) {
      await runWithTimeout("pnpm", ["-C", dst, "dev", "down", "--all"], 10_000);
    }
  }
  // Wipe everything under the fixture root and origins unconditionally. The
  // fixture template lives in /opt/alignfirst-developer-tests/fixtures/ and is re-copied below.
  // pnpm's store is pinned to /home/claw/.pnpm-store via ~/.npmrc, so nothing
  // here is worth keeping.
  for (const entry of readdirSync(PRIMARY)) {
    rmSync(`${PRIMARY}/${entry}`, { recursive: true, force: true });
  }
  createProjectsDirectory(PRIMARY, PRIMARY_MARKER);
  createProjectsDirectory(EXTERNAL, EXTERNAL_MARKER);
  createProjectsDirectory(LIFECYCLE, LIFECYCLE_MARKER);
  rmSync(ORIGINS, { recursive: true, force: true });
  mkdirSync(ORIGINS, { recursive: true });
  for (const fixture of FIXTURES) {
    await resetFixture(fixture);
  }
}

function createProjectsDirectory(path, marker) {
  mkdirSync(path, { recursive: true });
  writeFileSync(`${path}/.alignfirst-projects.json`, `${JSON.stringify(marker, null, 2)}\n`);
}

async function resetFixture({ name, parent, basePort }) {
  const dst = `${parent}/${name}`;
  cpSync(TEMPLATE, dst, { recursive: true, preserveTimestamps: true });
  patchFixture(dst, name, basePort);
  // alcode refuses to run outside a project that has a `.plans/` directory
  // (its coaching-session logs land there). Seed an empty one — the fixture's
  // .gitignore already ignores `.plans/`, so it stays untracked like a real
  // repo; the agent runs alcode from this project's canonical main path.
  mkdirSync(`${dst}/.plans`, { recursive: true });
  // The main worktree never runs `workspace setup`, so seed its `local.env`
  // (gitignored) from the committed example — the first port of its block.
  // Linked worktrees get theirs generated by the workspace tooling.
  cpSync(`${dst}/local.env.example`, `${dst}/local.env`);
  const gitEnv = {
    ...process.env,
    GIT_AUTHOR_NAME: "test",
    GIT_AUTHOR_EMAIL: "test@local",
    GIT_COMMITTER_NAME: "test",
    GIT_COMMITTER_EMAIL: "test@local",
  };
  runGit(dst, ["init", "-q", "-b", BASE_BRANCH], gitEnv);
  runGit(dst, ["add", "-A"], gitEnv);
  runGit(dst, ["commit", "-q", "-m", "fixture init"], gitEnv);

  // Bare `origin` seeded with the fixture's initial commit, so the working tree
  // is an up-to-date clone: `git fetch` finds the remote and
  // `git merge --ff-only origin/<base>` is a clean no-op. `origin/HEAD` points
  // at the base branch so `git remote show origin` reports it as the default.
  const origin = `${ORIGINS}/${name}.git`;
  runGit(dst, ["init", "-q", "--bare", "-b", BASE_BRANCH, origin], gitEnv);
  runGit(dst, ["remote", "add", "origin", origin], gitEnv);
  runGit(dst, ["push", "-q", "-u", "origin", BASE_BRANCH], gitEnv);
  // A `production` branch too, so the remote matches DEVELOPERS.md's convention
  // (base `main`, production `production`) and `git branch -a` reads realistically.
  runGit(dst, ["push", "-q", "origin", `${BASE_BRANCH}:refs/heads/production`], gitEnv);
  runGit(dst, ["remote", "set-head", "origin", BASE_BRANCH], gitEnv);
}

// Per-name patches applied to the materialized copy of the shared template.
// The package `name`, the entry-point H1s and the port block diverge — the live
// directory name is what actually matters. Patching only the `name` field of
// package.json keeps the frozen lockfile valid, so a single build-time install
// serves both projects.
function patchFixture(dst, name, basePort) {
  const pkgPath = `${dst}/package.json`;
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
  pkg.name = `@alignfirst-developer-tests/${name}-fixture`;
  writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);

  const config = {
    schemaVersion: 1,
    ticketIdPattern: "^ABC-\\d+$",
    portRange: { first: basePort, last: basePort + 19 },
  };
  writeFileSync(`${dst}/.alignfirst.json`, `${JSON.stringify(config, null, 2)}\n`);

  // Both entry points name the project, so the three otherwise identical copies
  // read distinctly — the app itself stays the "Comparables" product.
  const capitalized = name.charAt(0).toUpperCase() + name.slice(1);
  patchHeading(`${dst}/README.md`, /^# Comparables$/m, `# ${capitalized}`);
  patchHeading(`${dst}/DEVELOPERS.md`, /^# Developer Guide$/m, `# ${capitalized} Developer Guide`);

  patchBasePort(dst, basePort);
}

// An unmatched pattern would ship an unpersonalized fixture, silently weakening
// every scenario that asserts which project the agent read. Fail loudly instead.
function patchHeading(path, pattern, heading) {
  const content = readFileSync(path, "utf8");
  if (!pattern.test(content)) {
    throw new Error(`heading ${pattern} not found in ${path}`);
  }
  writeFileSync(path, content.replace(pattern, heading));
}

// The template is written for the first fixture's block, so the second one has
// to move: `base` in the workspace wrapper, and the committed example the main
// worktree's `local.env` is seeded from.
function patchBasePort(dst, basePort) {
  const wrapperPath = `${dst}/scripts/workspace/workspace.mjs`;
  const wrapper = readFileSync(wrapperPath, "utf8").replace(
    /^(\s*base:\s*)\d+(,)$/m,
    `$1${basePort}$2`,
  );
  writeFileSync(wrapperPath, wrapper);

  const examplePath = `${dst}/local.env.example`;
  const example = readFileSync(examplePath, "utf8").replace(/^PORT=.*$/m, `PORT=${basePort}`);
  writeFileSync(examplePath, example);
}

function runGit(cwd, args, env) {
  const r = spawnSync("git", args, { cwd, env, stdio: "inherit" });
  if (r.status !== 0) {
    throw new Error(`git ${args.join(" ")} (cwd=${cwd}) exited ${r.status}`);
  }
}

function runWithTimeout(cmd, args, timeoutMs) {
  return new Promise((resolve) => {
    const child = spawn(cmd, args, { stdio: "ignore" });
    const timer = setTimeout(() => child.kill("SIGKILL"), timeoutMs);
    child.on("exit", () => {
      clearTimeout(timer);
      resolve();
    });
    child.on("error", () => {
      clearTimeout(timer);
      resolve();
    });
  });
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
